@file:Suppress("TooGenericExceptionCaught")

package blazern.lexisoup.core.audio

import arrow.core.Either
import arrow.core.left
import arrow.core.right
import blazern.lexisoup.domain.error.Err
import kotlinx.cinterop.BetaInteropApi
import kotlinx.cinterop.ExperimentalForeignApi
import kotlinx.cinterop.ObjCObjectVar
import kotlinx.cinterop.alloc
import kotlinx.cinterop.memScoped
import kotlinx.cinterop.ptr
import kotlinx.cinterop.value
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.IO
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import platform.AVFoundation.AVKeyValueStatusCancelled
import platform.AVFoundation.AVKeyValueStatusFailed
import platform.AVFoundation.AVKeyValueStatusLoaded
import platform.AVFoundation.AVPlayer
import platform.AVFoundation.AVPlayerItemDidPlayToEndTimeNotification
import platform.AVFoundation.AVURLAsset
import platform.AVFoundation.currentItem
import platform.AVFoundation.pause
import platform.AVFoundation.play
import platform.AVFoundation.playable
import platform.AVFoundation.seekToTime
import platform.CoreMedia.CMTimeMake
import platform.Foundation.NSError
import platform.Foundation.NSNotificationCenter
import platform.Foundation.NSOperationQueue
import platform.Foundation.NSURL
import platform.darwin.NSObjectProtocol
import kotlin.concurrent.Volatile
import kotlin.coroutines.resume

/**
 * NOTE: this class is entirely generated by ChatGPT.
 */
internal class IosAudioPlayer(
    private val url: NSURL?,
    private val dispatcher: CoroutineDispatcher = Dispatchers.IO,
) : AudioPlayer {

    private val mutex = Mutex()

    @Volatile
    private var released = false

    private var player: AVPlayer? = null
    private var endObserver: NSObjectProtocol? = null

    private val _state = MutableStateFlow<AudioPlayer.State>(AudioPlayer.State.NotPlaying())
    override val state = _state.asStateFlow()

    override suspend fun play(): Either<Err, Unit> = withContext(dispatcher) {
        if (released) error("play: the player was released")

        mutex.withLock {
            val ensuredPlayer = ensurePlayer()
                ?: return@withLock Err("Could not create AVPlayer for $url").left()

            return@withLock try {
                ensuredPlayer.play()
                _state.update { AudioPlayer.State.Playing() }
                Unit.right()
            } catch (e: Exception) {
                Err.from(e).left()
            }
        }
    }

    @OptIn(ExperimentalForeignApi::class)
    override suspend fun reset(): Either<Err, Unit> = withContext(dispatcher) {
        if (released) error("reset: the player was released")

        mutex.withLock {
            val currentPlayer = player
            if (currentPlayer == null) {
                _state.update { AudioPlayer.State.NotPlaying() }
                return@withLock Unit.right()
            }

            return@withLock suspendCancellableCoroutine<Either<Err, Unit>> { continuation ->
                try {
                    currentPlayer.pause()
                    currentPlayer.seekToTime(CMTimeMake(value = 0, timescale = 1)) { finished ->
                        _state.update { AudioPlayer.State.NotPlaying() }
                        if (continuation.isActive) {
                            if (finished) {
                                continuation.resume(Unit.right())
                            } else {
                                continuation.resume(Err("Seek to start was interrupted").left())
                            }
                        }
                    }
                } catch (e: Exception) {
                    if (continuation.isActive) {
                        continuation.resume(Err.from(e).left())
                    }
                }
            }
        }
    }

    override fun release() {
        released = true
        _state.update { AudioPlayer.State.NotPlaying() }

        val observer = endObserver
        if (observer != null) {
            NSNotificationCenter.defaultCenter.removeObserver(observer)
            endObserver = null
        }

        player?.pause()
        player = null
    }

    private suspend fun ensurePlayer(): AVPlayer? {
        val url = url ?: return null
        player?.let { return it }

        when (validateUrlAsset(url)) {
            is Either.Left -> return null
            is Either.Right -> Unit
        }

        val createdPlayer = AVPlayer(uRL = url)
        installDidPlayToEndObserver(createdPlayer)

        player = createdPlayer
        return createdPlayer
    }

    @OptIn(ExperimentalForeignApi::class, BetaInteropApi::class)
    private suspend fun validateUrlAsset(url: NSURL): Either<Err, Unit> =
        suspendCancellableCoroutine { continuation ->
            try {
                val asset = AVURLAsset(uRL = url, options = null)
                val key = "playable"

                asset.loadValuesAsynchronouslyForKeys(listOf(key)) {
                    memScoped {
                        val error = alloc<ObjCObjectVar<NSError?>>()
                        val status = asset.statusOfValueForKey(key, error.ptr)

                        val result = when (status) {
                            AVKeyValueStatusLoaded -> {
                                if (asset.playable) {
                                    Unit.right()
                                } else {
                                    Err("Asset is not playable: $url").left()
                                }
                            }
                            AVKeyValueStatusFailed -> {
                                val nsError = error.value
                                if (nsError != null) {
                                    Err.from(Exception(nsError.localizedDescription)).left()
                                } else {
                                    Err("AVAsset failed to load: $url").left()
                                }
                            }
                            AVKeyValueStatusCancelled -> {
                                Err("AVAsset loading was cancelled: $url").left()
                            }
                            else -> {
                                Err("AVAsset did not become playable: $url").left()
                            }
                        }

                        if (continuation.isActive) {
                            continuation.resume(result)
                        }
                    }
                }
            } catch (e: Exception) {
                if (continuation.isActive) {
                    continuation.resume(Err.from(e).left())
                }
            }
        }

    @OptIn(ExperimentalForeignApi::class)
    private fun installDidPlayToEndObserver(player: AVPlayer) {
        endObserver?.let { NSNotificationCenter.defaultCenter.removeObserver(it) }

        endObserver = NSNotificationCenter.defaultCenter.addObserverForName(
            name = AVPlayerItemDidPlayToEndTimeNotification,
            `object` = player.currentItem,
            queue = NSOperationQueue.mainQueue,
        ) { _ ->
            player.seekToTime(CMTimeMake(value = 0, timescale = 1))
            _state.update { AudioPlayer.State.NotPlaying() }
        }
    }
}

private fun Err(message: String): Err = Err.from(IllegalStateException(message))
