name: on-pull-request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  update-yarn-lock-for-dependabot:
    runs-on: ubuntu-latest
    permissions:
      # To make & push a commit
      contents: write
      # To post a comment to the PR
      pull-requests: write
    outputs:
      sha: ${{ steps.push.outputs.sha }}
    steps:
      - uses: actions/checkout@v5
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Gradle
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Update yarn lock
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        working-directory: lexisoup-kmp
        run: ./gradlew kotlinUpgradeYarnLock

      - name: Make and push a commit if any diff
        id: push
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        run: |
          if git diff --quiet; then exit 0; fi
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add lexisoup-kmp/kotlin-js-store/yarn.lock
          git commit -m "dependabot: update Kotlin yarn.lock"
          git push
          NEW_SHA="$(git rev-parse HEAD)"
          echo "sha=$NEW_SHA" >> "$GITHUB_OUTPUT"

      # The PR will not get new checks started because the new commit was pushed with ${{ github.token }},
      # and this is by (Github's) design: we want to avoid workflows starting other workflows indefinitelly,
      # even if the possibility of such a bug is tiny.
      - name: Comment on PR with run link
        if: github.event.pull_request.user.login == 'dependabot[bot]' && steps.push.outputs.sha != ''
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          gh pr comment "${{ github.event.pull_request.number }}" --body "$(cat <<EOF
          ‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️
          ## **Updated \`lexisoup-kmp/kotlin-js-store/yarn.lock\` and pushed a commit.**
          # This PR will no longer show checks, but they are here:
          ${RUN_URL}
          ‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️
          EOF
          )"

      # At least 1 step that does at least something, just in case the entire
      # job is considered as skipped because all steps were skipped
      - run: echo "noop"

  build-and-test:
    needs: update-yarn-lock-for-dependabot
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Possibly move to updated commit
        if: needs.update-yarn-lock-for-dependabot.outputs.sha != ''
        run: |
          git fetch origin ${{ github.head_ref }}
          git checkout ${{ github.head_ref }}
          git reset --hard ${{ needs.update-yarn-lock-for-dependabot.outputs.sha }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Run detekt
        working-directory: lexisoup-kmp
        run: ./gradlew detekt --continue

      - name: Run tests
        working-directory: lexisoup-kmp
        run: ./gradlew 'testAndroidHostTest'

      - name: Tests results
        if: failure()
        run: |
          for report in $(find lexisoup-kmp -path "*/build/reports/tests/*UnitTest/index.html"); do
            echo "# Test: $(basename $(dirname $(dirname $(dirname $(dirname $(dirname "$report"))))))" >> $GITHUB_STEP_SUMMARY
            cat "$report" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
          done

      - name: Build release to ensure it is working
        working-directory: lexisoup-kmp
        run: ./gradlew bundleRelease

      - name: Build JS to ensure it is working
        working-directory: lexisoup-kmp
        run: ./gradlew jsBrowserDistribution

      - name: Automerge
        if: github.event.pull_request.user.login != 'dependabot[bot]'
        run: gh pr merge --delete-branch --merge --auto ${{ github.head_ref }}
        env:
          GH_TOKEN: ${{ github.token }}
